config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login' => 'session#new'
    post '/login' => 'session#create'
    delete '/logout' => 'session#destroy'

    # get '/transactions/new' => 'transactions#new'

root 'session#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord

belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :fetch_user

require 'securerandom'

  private
      def lucky_number
        @lucky_number = Random.rand(1..100)
      end

      def fetch_user
        @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
        session[:user_id] = nil unless @current_user.present?
      end



end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    username = params["username"]
    password = params["password"]

    user = User.find_by(username: username)
    # If the user exists and you provided the right password
    if user.present? && user.authenticate(password)

      session[:user_id] = user.id
      redirect_to "/users"

    else
      flash[:login_error] = "The password or email was incorrect"
      # Show the login form again (potentially with a temporary message)
      render :new # Show the new form
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/users"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all


    respond_to do |format|
        format.html
        format.json
      end

  end




  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new


  end

def create
transaction = Transaction.new(transaction_params)
transaction.token = SecureRandom.hex(6)
transaction.user_id = @current_user.id
transaction.save
redirect_to "/users/#{@current_user.id}"


end



private

def transaction_params
  params.require(:transaction).permit(:token, :description, :amount)
end

  def authorise
    unless @current_user
  flash[:error] = "You need to be logged in for that"
  redirect_to "/login"

    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_out, only: [:new, :create]
  before_action :check_if_logged_in, only: [:edit, :update]

  def index
  end

  def show
    id = params["id"]
    @user = User.find_by(id: params["id"])
    @transactions = Transaction.where(user_id: @current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path( @user )
    else
      render :new # Show them the Sign Up form again
    end
  end

  def edit
  end


  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def check_if_logged_out
      if @current_user
        flash[:error] = "You are already logged in"
        redirect_to "/users"
      end
    end

    def check_if_logged_in
      unless @current_user
        flash[:error] = "You need to be logged in for that"
        redirect_to "/login"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserAuthentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
    <!-- <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/skeleton.css"> -->
  </head>

  <body>



    <%= flash[:error] %>

    <nav>
      <% if @current_user %>
        <%= link_to "Log Out", "/logout", method: :delete %>
        <%= link_to @current_user.username, user_path(@current_user) %>
        <%= link_to "Edit Profile", edit_user_path(@current_user) %>
      <% else %>
        <%= link_to "Login", "/login" %>
        <%= link_to "Sign Up", "/users/new" %>
      <% end %>
    </nav>
    <%= yield %>

      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/session/new.html.erb
<h1>Login</h1>

<% if flash[:login_error] %>
  <p>
    <%= flash[:login_error] %>
  </p>
<% end %>

<%= form_tag "/login" do %>
  <p>
    <%= label_tag :username %>
    <%= text_field_tag :username %>
  </p>
  <p>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </p>

  <%= submit_tag "Login" %>
<% end %>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :transaction_description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_area :amount, id: :transaction_amount %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.token %></td>
        <td><%= transaction.description %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @transaction.token %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/users/_form.html.erb
<% unless @user.errors.full_messages.empty? %>

  <% @user.errors.full_messages.each do |msg| %>
    <p>
      <%= msg %>
    </p>
  <% end %>

<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username, required: true %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password, required: true %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, required: true %>
  </p>

  <%= f.submit %>

  <table>
    <thead>
      <tr>
        <th>Token</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.token %></td>
          <td><%= transaction.description %></td>
        </tr>
      <% end %>
    </tbody>







<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= session["important"] %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: "form" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<form>
<div class = "row">
  <label for="exampleRecipientInput">Select your financial institution</label>
    <select id="bankList"></select>
    <!-- <div class="six columns"> -->
     <label for="exampleEmailInput">Client ID</label>
     <input type="text" placeholder="client id" id="clientId">
     <label for="exampleEmailInput">Password</label>
     <input type="text" placeholder="password" id="password">
   <!-- </div> -->
  </div>
</div>
</form>

<!-- <a href="/transactions/new" class="newCode">new code</a> -->



<a class="button button-primary" href="/transactions/new">New Code</a>

<a class="button button-primary" id="getUserDetails">Get Latest Transactions</a>


<h2>Still To Receive</h2>

<table class="u-full-width">
<thead>
    <tr>
  <th>Token</th>
<th>Description</th>
<th>Amount</th>
    </tr>
  </thead>
<tbody>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.token %></td>
      <td><%= transaction.description %></td>
        <td><%= transaction.amount %></td>
    </tr>
  <% end %>
</tbody>
</table>


<div id ="calendar">
  <header>
    <h2>June 2017</h2>
  </header>
<table>
  <tr>
    <td>S</td>
    <td>M</td>
    <td>T</td>
    <td>W</td>
    <td>Th</td>
    <td>F</td>
    <td>S</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td>1</td>
    <td>2</td>
    <td>3</td>
    <td>4</td>
    <td>5</td>
  </tr>
  <tr>
    <td>6</td>
    <td>7</td>
    <td>8</td>
    <td>9</td>
    <td>10</td>
    <td>11</td>
    <td>12</td>
  </tr>
  <tr>
    <td>13</td>
    <td>14</td>
    <td>15</td>
    <td>16</td>
    <td>17</td>
    <td>18</td>
    <td>19</td>
  </tr>
  <tr>
    <td>20</td>
    <td>21</td>
    <td>22</td>
    <td>23</td>
    <td>24</td>
    <td>25</td>
    <td>26</td>
  </tr>
  <tr>
    <td>27</td>
    <td>28</td>
    <td>29</td>
    <td>30</td>
    <td>31</td>
    <td></td>
    <td></td>
  </tr>
</table>
</div>


</body>



<!--
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> -->

<h2>Paid</h2>

<table class="u-full-width" id="transactions">
  <thead>
    <tr>
  <th>id</th>
  <th>date</th>
  <th>amount</th>
    </tr>
  </thead>
 <tbody>
<tr></tr>
    </tbody>
</table>